CMakeLists.txt, taskflow.hpp, unittest/taskflow.cpp
Add reduce function and unittest into taskflow.hpp, unittest/taskflow.cpp. Add reduce test into CMakeLists.txt.
=> Add reduce function and its unittest

taskflow.hpp
- this is in the same vein as the Threadpool::async() fix in PR #22,
which is required to use Taskflow::emplace() with Visual Studio 2017.
See description (comments) in #21.
=> emplace() compile fix for Visual Studio

CMakeLists.txt, example/threadpool_cxx14.cpp, taskflow/threadpool/threadpool.hpp, taskflow/threadpool/threadpool_cxx14.hpp, unittest/threadpool_cxx14.cpp
(and add a unit test for this feature)
This was suggested (by me ;-) in issue #36.
=> Add wait_for_all() method to Threadpool

CMakeLists.txt, example/threadpool.cpp, taskflow/threadpool/proactive_threadpool.hpp, unittest/threadpool.cpp
I have added ProactiveThreadpool and its associated test examples
=> ProactiveThreadpool

awesome-parallel-computing.md
Added coro-async library to awesome-parallel-computing resources
=> Added coro-async library to awesome-parallel-computing resources

README.md
=> dead link to DtCraft

CMakeLists.txt
- feel free to personalize with your need's.
=> feat(cmake-target): add cmake target instead of global settings

CMakeLists.txt
Please update Vcpkg port after that merge
=> feat(Apple): add support for AppleClang 11.0

taskflow/core/executor.hpp
=> Fix for #133

examples/reduce.cpp
was checking for inequality before.
=> strcmp needs to check for 0 for equality.

taskflow/core/observer.hpp
Related to https://github.com/cpp-taskflow/cpp-taskflow/issues/166.
=> size_t instead of unsigned

doxygen/cookbook/Chapter1.dox, doxygen/cookbook/Chapter2.dox
Found while looking at the examples. :-)
=> fix a few documentation typos

CMakeLists.txt, TaskflowConfig.cmake.in
=> Add Threads target to taskflow interface library and Update Packate Config

taskflow/core/executor.hpp
=> remove extra semicolon

taskflow/core/algorithm/for_each.hpp, taskflow/core/algorithm/reduce.hpp, taskflow/core/executor.hpp, taskflow/core/graph.hpp, taskflow/core/notifier.hpp, taskflow/utility/serializer.hpp
I like to turn on compiler sign conversion warnings. This PR fixes a few warnings I see on my system.
=> fix a few warnings

CMakeLists.txt
This merge request is to fix issue #296.
=> Use relative install path

taskflow/core/graph.hpp, taskflow/core/task.hpp
=> Enable users to associate arbitrary data with a Task

README.md
corret ```tf::future``` into ```tf::Future```
=> fix a trivial bug in 'Launch Asynchronous Tasks'

doxygen/examples/wavefront.dox
Prevent compilation error when building wavefront example.
=> Define num_blocks

taskflow/core/tsq.hpp
winspool.h has a define MAX_PRIORITY. If that header is included somewhere along the lines along with taskflow.hpp then build errors occur. Simply prepending TF_ to the MAX_PRIORITY template parameter resolves this collision.
=> Renamed MAX_PRIORITY to TF_MAX_PRIORITY

taskflow/core/executor.hpp
Allow to disable exception handling, this makes it easier to generate stack traces as it lets the exceptions be unhandled and terminate where they were generated
Related to this https://github.com/taskflow/taskflow/issues/266
=> add a way to just let an unhandled exception be unhandled

doxygen/cookbook/async_tasking.dox
=> Show the correct function to be called: corun_all() instead of join().

CMakeLists.txt
fix https://github.com/taskflow/taskflow/issues/586
=> fix wrong cmake file path include

taskflow/core/semaphore.hpp
=> fix documentation of Semaphore::release

examples/simple.cpp
Add names to tasks A, B, C, and D for better identification in Graphviz
Add taskflow dump for profile.
=> feat(examples): Add names to tasks in simple

taskflow/core/error.hpp
fix issue https://github.com/taskflow/taskflow/issues/565
=> build: support build w/ no-exception

taskflow/core/runtime.hpp, unittests/test_runtimes.cpp
Closes https://github.com/taskflow/taskflow/issues/660.
=> feat: add `is_cancelled` to `tf::Runtime`

taskflow/core/async.hpp
MSVC fails to compile "#include <taskflow/core/executor.hpp>" with error "undefined type 'tf::Runtime'" in line 72 of `async.hpp`. Issue is reproducible both for `v3.9.0` release and on latest commit of `master` branch `b92974af588ada2904a6a95c61af4b2e36f150c7`.
```log
...\taskflow/core/async.hpp(72): error C2027: use of undefined type 'tf::Runtime'
...\taskflow\core\declarations.hpp(15): note: see declaration of 'tf::Runtime'
...\taskflow\core\executor.hpp(1128): note: This diagnostic occurred in the compiler generated function 'auto tf::Executor::_async(P &&,F &&,tf::Topology *,tf::Node *)'
...\taskflow/core/async.hpp(256): error C2027: use of undefined type 'tf::Runtime'
...\taskflow\core\declarations.hpp(15): note: see declaration of 'tf::Runtime'
...\taskflow\core\executor.hpp(1052): …
```
=> Fix undefined type 'tf::Runtime' error for MSVC

taskflow/core/executor.hpp
Disable try/catch in executor if TF_DISABLE_EXCEPTION_HANDLING defined
=> Toggle try/catch in executor
