example/matrix.cpp
taskflow.hpp

Fixing compile for visual studio. Repaired the matrix example openmp "index must be signed integer" error, and fixed a if constexpr issue. It still has a huge amount of warnings.

Compile fix for visual studio.

---

README.md
threadpool.hpp

- if you're using a C++17 compiler, you should include the main
"taskflow.hpp" header. However, if you're working on a C++14 project
and only require the Threadpool functionality, you may include
"threadpool.hpp".

Add threadpool.hpp (C++14 "light" version, only including tf::Threadpool)

---

CMakeLists.txt
README.md
example/multiple_dispatch.cpp
unittest/threadpool.cpp
unittest/threadpool_cxx14.cpp

- add multiple_dispatch example, which illustrates dispatching
multiple taskflow graphs as independent batches (which all run on
the same taskpool).
- update README to include all recently-added examples.
- (unrelated) fix compile warnings on Visual Studio.

Add multiple_dispatch example

---

example/data_flow.cpp

Here is an example how to pass data from tasks to their successors and to use cpp-taskflow for synchronization.
In real world code probably some kind of factory class will ensure all the invariants, but I think it is quite small to show the point.

Add an example about a way to pass data between tasks

---

example/dataflow.hpp
example/dice_pools.cpp
example/get_best_dice.cpp

The class is a thin wrapper around taskflow that ensures that each arc in the taskflow DAG has a associated object (of type T) and allows nodes to execute a function that can easily read from the incoming arcs objects and write in the outcoming arcs objects.
All arcs are associated with an object of the same type T. Since the graph is built runtime it would be really difficult to do otherwise. If one needs different types of objects on the arcs, then one can use class hierarchies and virtual functions and the type T would be a unique_ptr<some base class>. Otherwise one can use std::variant.
The new example is an extension of the previous one. It wants to show that with a bit of boiler plate code that give human-readable names to the objects on the incoming and outcoming arcs it is …

Add a ready-to-use generic class to associate data to the flows

---

taskflow/executor/workstealing.hpp

To fix the following warning (from clang 6):
```
cpp-taskflow/taskflow/executor/workstealing.hpp:492:37: warning: lambda capture 'N' is not used [-Wunused-lambda-capture]
_threads.emplace_back([this, i, N] () -> void {
^
```

Fix unused-lambda-capture clang-warning

---

README.md

- Point to correct folder `examples` instead of `example`.
- Fix code snippet with call to `run_until(...)`.

Fix typos and paths

---

taskflow/core/executor.hpp
taskflow/core/graph.hpp
taskflow/core/topology.hpp

This eliminates quite some warnings for MSVC++.

size_t instead of int

---

taskflow/utility/object_pool.hpp

Fix gcc-9 -Wpedantic warning about extra semicolon. All uses have a
semicolon at the end so remove from the macro.

remove extra semicolon

---

CMakeLists.txt

This PR fix an issue with x64-windows. Compile with /bigobj for x64-windows target. I will also use this as a patch to update the VCPKG port

Compile with /bigobj on MSVC

---

CMakeLists.txt
TaskflowConfig.cmake.in

Changes the install location of the package configuration file from `${TF_LIB_INSTALL_DIR}/cmake` to `${TF_LIB_INSTALL_DIR}/cmake/${PROJECT_NAME}`. This matches the typical install location according to [this](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html) where it states
> The find_package() command may be used to search for the package configuration file. This command constructs a set of installation prefixes and searches under each prefix in several locations. Given the name Foo, it looks for a file called FooConfig.cmake or foo-config.cmake. The full set of locations is specified in the find_package() command documentation. One place it looks is:
> 
> `<prefix>/lib/cmake/Foo*/`
The current install location creates a problem since it is not a search location as shown …

Change CMake install location

---

taskflow/algorithm/parallel_for.hpp

I forgot one as I was only specializing the default schedule.

Added static_cast for double to size_t conversion

---

taskflow/utility/object_pool.hpp
taskflow/utility/passive_vector.hpp
taskflow/utility/uuid.hpp

Fix for the reported issue #242

Prevent min max macros expansion when windows.h header is included in project alongside taskflow

---

CMakeLists.txt
README.md
taskflow/core/task.hpp

This pull request is in response to issue #248. Versions of the intel C++ compiler icpc above v19.0.1 are known to support the C++17 core language features (see here https://en.cppreference.com/w/cpp/compiler_support). I have tested this pull request with versions v19.0.3.199 (2019-02-06)  and v19.1.3.304 (2020-09-25) of icpc.

Add support for the Intel C++ compiler

---

taskflow/core/executor.hpp
taskflow/core/graph.hpp
taskflow/core/taskflow.hpp
taskflow/core/topology.hpp
taskflow/utility/os.hpp
unittests/basics.cpp

Sir,
Ojas Mithbavkar here. I had discussed with you a method involving a new function called _tear_cancelled_topology. You had suggested checking for the destruction of topology before completion of all references. It appears that such a case was happening in case of dynamic tasks. Hence I have devised a new method based on the join_counter.
In the normal run, the join_counter of the tpg keeps track of whether the node is last or not before tearing down the tpg. For cancelling, once the is_cancel flag is set to True, we prevent the execution of the function given to the node. 
```
if (!node->_topology->is_cancel){
std::get<Node::StaticTask>(node->_handle).work();
}
```
Next, we prevent any scheduling of its successors. 
```
if(--(node->_successors[i]->_join_counter) == 0) {
if …
```

Cancelling a taskflow

---

taskflow/utility/serializer.hpp

As we need to call `_device.read()`, the default template argument `Device` should be type of `std::istream`, I guess it was a copy-paste error.

fix template argument

---

taskflow/core/algorithm/sort.hpp

parallel_pdqsort's recursive async lambda call to parallel_pdqsort was capturing a reference to Compare on caller function stack which isn't guaranteed to remain valid due to nature of Subflow::silent_async call; made it capture by value instead
https://github.com/taskflow/taskflow/issues/337

Fix for FlowBuilder::sort due to by ref lambda capture of comparator function (issue #337)

---

taskflow/core/flow_builder.hpp
taskflow/core/graph.hpp

I decided to add `Graph::erase` with `node_pool.recycle()` invocation inside to mirror `Graph::emplace` which invokes `node_pool.animate()`.

Add erase to taskflow and graph

---

TaskflowConfig.cmake.in

Currently we have the problem that if Taskflow is installed into a directory and then later on this installation is moved into another directory, the cmake find_package routine doesn't succeed. This is a [problem for the hunter package manager](https://github.com/cpp-pm/hunter/pull/470#issuecomment-923731949) and I think also other package managers may have this problem.
The Root cause of this is line 3 in TaskflowConfig.cmake.in where the include directory path gets hardcoded. When the installation is moved to another directory later on, this hardcoded path persists and causes an exception when `set_and_check` is called on line 3.
My proposed change fixes this problem by retrieving the include path from the cmake target `Taskflow::Taskflow`. In this way we can reuse the rather …

Make CMake installation relocatable

---

taskflow/core/executor.hpp
taskflow/core/graph.hpp
taskflow/core/taskflow.hpp

This PR aims to increase the compatibility of the taskflow library with older versions of macOS.
Trying to build Python wheels for our project that incorporates taskflow showed that targeting macOS yields several errors stating that std::variant's `std::get` is not available.
For an example of this see https://github.com/iic-jku/ddsim/runs/3732494041?check_suite_focus=true#step:4:280.
The problem can be resolved by replacing `std::get` calls with the corresponding `std::get_if` equivalent (see also https://stackoverflow.com/a/53887048).

Inrease macOS compatibility

---

unittests/algorithm.cpp

In addition to testing tf::transform with `std::vector<T>` iterators,
we also test containers without fast random access iterators, e.g.
`std::list<T>`.

Test non-random accessible iterators

---

examples/CMakeLists.txt
taskflow/utility/os.hpp

These changes allowed building the library with emscripten, and running a few of the examples:
**build**
`emcmake cmake ...`
**run example with node.js**
`node --experimental-wasm-threads --experimental-wasm-bulk-memory examples/simple.js`

support emscripten build

---

README.md
docs/index.html

because there is`#include <taskflow/taskflow.hpp>`  in your simple.cpp, g++ doesn't need to specify another taskflow directory as -I parameter.
for example, when I run:
```bash
g++ -std=c++17 simple.cpp -I taskflow/taskflow -O2 -pthread -o simple
```
I receive this error message:
```
simple.cpp:1:10: fatal error: taskflow/taskflow.hpp: No such file or directory
1 | #include <taskflow/taskflow.hpp>  // Taskflow is header-only
|
```

fix compile command

---

taskflow/core/tsq.hpp
taskflow/utility/macros.hpp

`TaskQueue::push()` and `TaskQueue::pop()` are functions that are in critical hot code path and used only from few places. It makes sense to look into improving inlining decisions for these functions.
As compiled on x86_64 by gcc 10.2, `TaskQueue::push()` contains a number of function prologue and epilogue instructions. These are mostly needed for the case when the queue overflows and needs resizing, which happens extremely infrequently. Inlining the frequent code path and forbidding inlining of the infrequent code path should improve performance slightly.
`TaskQueue::pop()` on the other hand does not have much in function prologue and epilogue as it fits into caller-saved registers. However, the function is called from only 2 places, so inlining it too does not increase binary size too …

Improve inlining of critical functions of TaskQueue

---

benchmarks/data_pipeline/taskflow.cpp
benchmarks/data_pipeline/tbb.cpp

data_pipeline benchmark contains multiple definitions of the same symbol with external linkage, which causes link-time errors on Linux.

Fix duplicate symbol errors in benchmarks

---

CMakeLists.txt

Current cmake minimum version is set to cmake 3.12 in CMakeLists.txt. This version allows to define `CMAKE_CUDA_STANDARD` up to 14. Support for `CMAKE_CUDA_STANDARD` 17 and 20 have only been introduced recently in cmake 3.18.

Update cmake minimum version to 3.18

---

CMakeLists.txt

There are breaking changes in many minor Version upgrades, so the compatibility is really only between minor versions.
E.g. Version 3.6 introduced a couple oft breaking changes leading to build errors downstream https://github.com/maxbachmann/RapidFuzz/issues/329

Update compatibility guarantees

---

README.md

This PR adds a compiler explorer link on README with simple.cpp example. This can 
- easily onboard more users without any local environments
- enables both developers and users to perform live demo and quick verification
- reduces communication overhead among different local setups
- and more...

add compiler explorer link with simple.cpp on README

---

taskflow/cuda/cuda_memory.hpp

C++ 20 has removed the std::allocator<void>-specialisation, quick wokaround is to replace the type alias with the intended type. Fixes issue 539.

C++-20 compilation error fix

---

taskflow/algorithm/find.hpp
taskflow/algorithm/for_each.hpp
taskflow/algorithm/launch.hpp
taskflow/algorithm/reduce.hpp
taskflow/algorithm/scan.hpp
taskflow/algorithm/transform.hpp

MSVC 19.29.30153 (C++17) seems to have trouble with the macro `TF_MAKE_LOOP_TASK`.
When building the parallel_for.cpp example, it yields the internal compiler error. Changing the TF_MAKE_LOOP_TASK to a templated function taking lambdas seem to fix the issue. 
I wonder if you like the fix or not, maybe you have some better idea?
The error when building commit 39c4b6d998f022dcd8cf6065d9c7b8b4de332542: 
```
Build started...
1>------ Build started: Project: parallel_for, Configuration: Release x64 ------
1>Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30153 for x64
1>Copyright (C) Microsoft Corporation.  All rights reserved.
1>cl /c /ID:\taskflow /W3 /WX- /diagnostics:column /O2 /Ob2 /D _MBCS /D WIN32 /D _WINDOWS /D NDEBUG /D "CMAKE_INTDIR=\"Release\"" /Gm- /EHsc /MD /GS /fp:precise …
```

fix compile error for MSVC 19.29.30153 for x64 (Visual studio 2019)

---

CMakeLists.txt
LICENSE
cmake/CheckAtomic.cmake
examples/CMakeLists.txt
examples/cuda/CMakeLists.txt
examples/sycl/CMakeLists.txt
tfprof/server/CMakeLists.txt
unittests/CMakeLists.txt
unittests/cuda/CMakeLists.txt
unittests/sycl/CMakeLists.txt

This patch appears to fix the undefined reference to `__atomic_*_8` issue (#578).  I might have specified `${ATOMIC_LIBRARY}` more than needed, but everything seems to compile with this patch (at least when applied to v3.6.0 rather than HEAD) both on an amd64 machine and on an armel machine.

Handle the need to explicitly link to libatomic on some archs (#578)

---

taskflow/utility/object_pool.hpp

`operator new` will throw `std::bad_alloc` if it cannot allocate enough space. It is not necessary to check the returned value against `nullptr`.

operator new() will never return a 'nullptr'.

---

taskflow/utility/iterator.hpp
unittests/test_for_each.cpp

**Problem description**: https://github.com/taskflow/taskflow/issues/610
Function `for_each_index` has following signature: `template <typename B, typename E, typename S, typename C, typename P> Task FlowBuilder::for_each_index(B beg, E end, S inc, C c, P part);` which implies, that range might be heterogeneous: for example, `beg` and `end` can be of type `size_t`, and `inc` can be `int`.
However, it's not the case, because C++ compilers fail to deduce type on functions `is_range_invalid` and `distance`, which are used under the hood of `for_each_index`, because they are homogeneous. So, before this pull-request, something like following example wouldn't compile, because compiler fails to deduce types of arguments for homogeneous functions `distance` and `is_range_invalid`:
``` …
```

Make `for_each_index` actually heterogeneous

---

doxygen/cookbook/executor.dox
doxygen/install/benchmark_taskflow.dox

As shown in the content of [benchmark/CMakeLists.txt](https://github.com/taskflow/taskflow/blob/master/benchmarks/CMakeLists.txt), all benchmark executable files now have the bench_ prefix. However, the documentation was not updated accordingly. I have made some updates to reflect these changes.
same variable name is wrong.
The contents of docs are generated by doxygen and m.css is tracked in repo, so need to update also. But the environment of mine is different from the default. Please update it by yourself @tsung-wei-huang

fix(docs): fix wrong varibale name and executable name in doxygen dox

---

doxygen/cookbook/conditional_tasking.dox

The original example code contains the following issues:
1. The expression `++c < 10 ? 0 : -1` should return 1 in the false case; otherwise, the executor will not be able to find the successor task to execute, and the final result of count will be 10.
2. A source task should be added; otherwise, the taskflow will encounter a "no source task" error.
3. Task A should also be a `loop` task and a predecessor task for (A, B).
Additionally, I have added some code to help newcomers debug and visualize the graph more easily.
Lastly, could someone please explain the purpose of the if(i) code block:
https://github.com/taskflow/taskflow/blob/master/doxygen/cookbook/conditional_tasking.dox#L515-518
Thanks advance.

bugfix(doxygen): update conditional tasking in doxygen/cookbook/conditional_tasking.dox

---

doxygen/Doxyfile
taskflow/core/executor.hpp
taskflow/core/graph.hpp
taskflow/core/taskflow.hpp

Original issue on the m.css repo: mosra/m.css#250
This PR excludes the `Executor` implementation from Doxygen processing as proposed in #605, just with a more unique name (@tjhei I listed you as a co-author). Additionally fixes warnings related to filesystem hierarchy by enabling FULL_PATH_NAMES + STRIP_FROM_PATH. That ultimately results in the same output as before, but with an effect that the directory structure doesn't have to be guessed from incomplete information by m.css. The warnings manifest as the following as of mosra/m.css@083c7a87dcca80027a4bc9c5e6db3bab4babffb0:
> WARNING:root:potential issue: the parent of algorithm/ is taskflow/ which is not a prefix, you may want to enable FULL_PATH_NAMES together with STRIP_FROM_PATH and STRIP_FROM_INC_PATH to preserve filesystem …

Fix the `Executor` class not appearing in generator docs, patch warnings

---

CMakeLists.txt

To avoid unnecessary test related targets when CMake build option `TF_BUILD_TESTS = OFF` we should only `include(CTest)` when `TF_BUILD_TESTS = ON`

only include CTest if building tests

---

taskflow/core/tsq.hpp
taskflow/taskflow.hpp

Fix AppleClang compile error in tsq.hpp with undeclared identifiers 'TF_DEFAULT_UNBOUNDED_TASK_QUEUE_LOG_SIZE' and 'TF_DEFAULT_UNBOUNDED_TASK_QUEUE_LOG_SIZE' (close #650)

Fix AppleClang compile error in tsq.hpp with undeclared identifiers

---

taskflow/algorithm/partitioner.hpp
taskflow/core/observer.hpp

This errors occur because the Windows` min `and `max` macros conflict with `std::min` and `std::max`.

Fix MSVC macro conflict

---

CMakeLists.txt

Create an ALIAS target that matches the exported target name (TaskFlow::Taskflow).  This allows consumers to be agnostic of how Taskflow was brought into the build.  ie: a consuming project may use `Taskflow::Taskflow` and it will work with an external packaging of Taskflow, and also when built-on-the-fly (eg: via git submodule).

Enable use of 'Taskflow::Taskflow' for all consumption styles

---

CMakeLists.txt

The current code uses the **__cplusplus** macro to detect C++ versions, but MSVC does not update this macro by default (it remains **199711L**). This causes incorrect version detection in Visual Studio.
This PR adds **/Zc:__cplusplus** to CMake compile options for MSVC, ensuring __cplusplus reflects the actual C++ standard.

fix CMakeLists.txt

---

CMakeLists.txt
README.md
doxygen/QuickStart.dox
doxygen/install/install.dox

Updating the minimal compiler versions in cmake printouts and documentation. This is assuming the checks in cmake are still correct

update compiler versions in docs and printouts
